### PR TITLE
code review

### PR DESCRIPTION
**Pull request by Escuro-JohnDenielL**
Please review my code. Thank you.

### CODE REVIEW

**Review by Villamarzo-Kazel — CHANGES_REQUESTED** [review]
I'm sorry my mistake

**Comment by Escuro-JohnDenielL** [comment]
@KazelVillamarzo Hello po, Meron naman pong spaces before { and after the selectors 
image
Can you elaborate po thank you

**Review by Villamarzo-Kazel — APPROVED** [review]

**Review by Villamarzo-Kazel — CHANGES_REQUESTED** [review]
in your script.js you used an arrow function that violated the coding guidelines 
pls refer to the coding guidelines.
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g29a1fb1fdca_2_0

**Review by Villamarzo-Kazel — CHANGES_REQUESTED** [review]
your script.js violates the coding guidelines in line 11 and 28 theres a function inside the function refer to the coding guidelines  

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g2651733a4ec_0_9

**Review by Villamarzo-Kazel — APPROVED** [review]
this code is approved.

**Comment by Escuro-JohnDenielL** [comment]
Thank you!

**Pull request merged**
